/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "Button_1_aliases.h"
#include "Button_1.h"
#include "Button_2_aliases.h"
#include "Button_2.h"
#include "isr_button.h"
#include "Pin_A_aliases.h"
#include "Pin_A.h"
#include "UART_LOG.h"
#include "Pin_B_aliases.h"
#include "Pin_B.h"
#include "Pin_C_aliases.h"
#include "Pin_C.h"
#include "Pin_D_aliases.h"
#include "Pin_D.h"
#include "Pin_E_aliases.h"
#include "Pin_E.h"
#include "Pin_F_aliases.h"
#include "Pin_F.h"
#include "Pin_G_aliases.h"
#include "Pin_G.h"
#include "Pin_DP_aliases.h"
#include "Pin_DP.h"
#include "Pin_SelA_aliases.h"
#include "Pin_SelA.h"
#include "PWM_Clock_1.h"
#include "RGB_PWM_Green_1.h"
#include "LED_green_1_aliases.h"
#include "LED_green_1.h"
#include "LED_Yellow_1_aliases.h"
#include "LED_Yellow_1.h"
#include "RGB_PWM_Yellow_1.h"
#include "RGB_PWM_Red_1.h"
#include "LED_red_1_aliases.h"
#include "LED_red_1.h"
#include "RGB_PWM_Yellow.h"
#include "LED_Yellow_aliases.h"
#include "LED_Yellow.h"
#include "RGB_PWM_Red.h"
#include "LED_red_aliases.h"
#include "LED_red.h"
#include "RGB_PWM_Green.h"
#include "LED_green_aliases.h"
#include "LED_green.h"
#include "PWM_Clock.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

